---
url: http://rocklov.hmg.com #ilustrando um ambiente de homologacao
mongo: mongodb://usuario@senha:200.234.55.77:27017/rocklov #ilustrando um ambiente num ip fixo q é acessado por usuario e senha