pipeline {
    agent {
        docker {
            image 'ruby'
            args '--network rocklov-network'
        }
    }

    stages {
        stage('Preparation'){
            steps{
                sh 'cd api && bundle install'
            }
        }
        stage('Testing') {
            steps {
                sh 'cd api && rspec'
            }
        }
        stage('UAT'){
            steps{
                echo 'Aguardando testes de aceitacao'
                input message: 'Podemos ir para producao?'
            }
        }
        stage('Prod'){
            steps{
                echo 'Api pronta para producao'
            }
        }
    }
    post {
        always {
            junit 'api/logs/report.xml'
        }
    }
}
